POST http://localhost:13000/database/init
Content-Type: application/json

###

GET http://localhost:13000/user/getUsers

###

POST http://localhost:13000/user/register
Content-Type: application/json

{
    "name": "rafly",
    "username": "rhangga",
    "password": "password"
}